language: python
python:
  - "3.9"
cache: pip

install:
  - pip install -r requirements.txt

script: 

  - coverage run --source=Travis_pruebas Test_Calculo.py
  - coverage report -m

after_success:
  - coveralls